35/content layout page
MarkDeKraker/T15-LifeBelowWater pull request #38
Opened 2024-05-19 16:13 UTC by Nelio-J

Informatiepagina's voor plasticvervuiling in de oceaan ingericht en gestyled. Ik heb ook met de Framer Motion library wat animaties toegevoegd.

De pagina's zijn te vinden op:
/plastic/probleem
/plastic/gevolgen
/plastic/aanpak

2024-05-23 14:50 UTC, faroeq33 requested changes
Comments te vinden in de bestanden

2024-05-23 14:50 UTC, faroeq33 commented on client/src/App.tsx
> +            <Route path="/plastic/gevolgen" element={<PlasticConsequences />} />
Maak daar PlastiConsequencesPage van

2024-05-23 14:50 UTC, faroeq33 commented on client/src/components/Plastic/PlasticApproach.tsx
> +      <TopicLink
Nest de Topic links in een 1 component en plaats dat op all je pagina's want nu moet je bij elke wijziging in de topic links veranderen op 3 plaatsen

2024-05-23 14:50 UTC, faroeq33 commented on client/src/components/Plastic/TopicComp.tsx
> +    <Link to={to} className={`colstart-${colStart} col-end-${colEnd} col-span-3 z-20`}>
colstart- moet gewijzigd worden naar col-start, anders gaat want nu staat je menu zoals op de volgende afbeelding
![faulty-menu](https://github.com/MarkDeKraker/T15-LifeBelowWater/assets/11407191/2e67a74e-5e20-4ff9-88b1-5361afb47462)

2024-05-23 14:54 UTC, luuknnh commented on client/src/components/Plastic/PlasticExampleComp.tsx
Ff de naam wijzigen van de component. 
Lijkt mij wel zo handig 😉

2024-05-25 20:49 UTC, faroeq33 approved these changes

2024-05-25 20:50 UTC, merged